language: python
python:
  - "3.2"
# - "2.7"
# - "3.3"
# whitelist
branches:
  only:
    - master
    - develop
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq ibus python3-gi gir1.2-ibus-1.0 gir1.2-wnck-3.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to run tests
script: nosetests --attr '!skip-travis'

notifications:
  irc:
    channels:
      - "chat.freenode.net#bogo"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}#%{commit} (%{author})"
      - "%{message}: %{build_url}"
